### ISSUE TITLE
Compare parameter to string?

### ISSUE THREAD

**Issue by marcblank** [ncalc/ncalc#370] opened 2024-12-06 03:25 UTC
If I have an Expression a = 'X' and a parameter named a with value 'X', the result is false.   Is this expected?

Expression e = new Expression("a = 'X'"); 
e.Parameters["a"] = 'X';      
e.Evaluate() -> false

I assume I'm missing something!

**Comment by Bykiev** [comment] 2024-12-06 15:06
Hi, what version of NCalc do you have installed?

**Comment by marcblank** [comment] 2024-12-06 18:49
3.6.0.8; thanks.

**Comment by Bykiev** [comment] 2024-12-06 18:59
I can't reproduce the issue with the latest version. This is quite old version, I'd recommend to install the latest version from NuGet: https://github.com/ncalc/ncalc

**Comment by marcblank** [comment] 2024-12-06 19:06
Thanks for the help.  I'm quite the noob with VS and NuGet.   I uninstalled 3.6 and installed 5.3 with the NuGet package manager in VS.   I get the errors above, and not sure what's to be done.   Any pointers would be appreciated... :-)

**Comment by Bykiev** [comment] 2024-12-06 19:20
It seems you're using [PanoramicData.NCalcExtensions](https://github.com/panoramicdata/PanoramicData.NCalcExtensions), unfortunately for now it's not compatible with this NCalc package (only supports it's fork CoreCLR-NCalc).
Other errors can be easily fixed:
- `EvaluateOptions` should be replaces with `ExpressionOptions`
- `Expression.ParsedExpression` property was renamed to `Expression.LogicalExpression`
- `LogicalExpressionVisitor` was replaced with `ILogicalExpressionVisitor`

**Comment by marcblank** [comment] 2024-12-06 19:33
Thanks; I actually wasn't even using Panoramic, so that's easy.

      class ParameterExtractionVisitor : ILogicalExpressionVisitor {
          public HashSet<string> Parameters = new HashSet<string>();

          public override void Visit(NCalc.Domain.Identifier function) {
              //Parameter - add to list
              Parameters.Add(function.Name);
          }

          public override void Visit(NCalc.Domain.UnaryExpression expression) {
              expression.Expression.Accept(this);
          }

          public override void Visit(NCalc.Domain.BinaryExpression expression) {
              //Visit left and right
              expression.LeftExpression.Accept(this);
              expression.RightExpression.Accept(this);
          }

          public override void Visit(NCalc.Domain.TernaryExpression expression) {
              //Visit left, right and middle
              expression.LeftExpression.Accept(this);
              expression.RightExpression.Accept(this);
              expression.MiddleExpression.Accept(this);
          }

          public override void Visit(Function function) {
              foreach (var expression in function.Expressions) {
                  expression.Accept(this);
              }
          }

          public override void Visit(LogicalExpression expression) {

          }

          public override void Visit(ValueExpression expression) {

          }
      }

![{521EE518-FE28-4C52-A680-4692732D8769}](https://github.com/user-attachments/assets/79ff7bc6-de73-4323-9d62-3ab1cd7ea086)

**Comment by marcblank** [comment] 2024-12-06 19:39
I'm just trying to pull out the parameters used in an Expression.

**Comment by marcblank** [comment] 2024-12-06 19:53
And where do I find the dll for the latest NCalc then?   Sorry for all the questions; WIndows/.NET/VS aren't my native language.

**Comment by marcblank** [comment] 2024-12-06 20:10
So running this, I see...
![{8CE59C8B-23A0-4BF8-BCF2-A049C31BEADF}](https://github.com/user-attachments/assets/629fcce5-44db-413d-879a-f61e06f62bfc)

**Comment by marcblank** [comment] 2024-12-06 20:22
Maybe best way to ask is:  What is the best way to simply extract all Identifiers from an expression?   Thanks.   @Bykiev

**Comment by marcblank** [comment] 2024-12-06 21:56
Ok, @Bykiev I have 5.0.0 (I can't use 5.3.0 because of a conflict with and I still see the behavior where a == 'x' returns false where parameter a is defined as 'x'.   Was this fixed later than 5.0.0?

**Comment by gumbarros** [comment] 2024-12-07 00:25
@marcblank 

You are probably looking for https://ncalc.github.io/ncalc/articles/values.html#chars

In the CLR 'X' is not equal to "X" (single quotes is char and double string)

**Comment by marcblank** [comment] 2024-12-07 00:28
Thanks.  I’ll look into that…

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by marcblank** [comment] 2024-12-07 01:30
Expression e = new Expression("a = 'XX'");
e.Parameters["a"] = 'XX';
e.Evaluate() -> false

Still doesn't work...

**Comment by marcblank** [comment] 2024-12-07 01:32
It doesn't work with 'XX' either...

-m

________________________________

**Comment by Bykiev** [comment] 2024-12-07 09:21
What is your culture? Try to specify it as the second parameter of `Expression`.



> Expression e = new Expression("a = 'XX'"); e.Parameters["a"] = 'XX'; e.Evaluate() -> false
> 
> Still doesn't work...

This is not a valid C# code, as chars can't store strings, should be  
```
Expression e = new Expression("a = 'XX'", CultureInfo.InvariantCulture); 
e.Parameters["a"] = "XX"; 
var res = e.Evaluate(); // result is true
```

**Comment by gumbarros** [comment] 2024-12-18 00:56
Closing because this is expected behavior.

**Closed by gumbarros** 2024-12-18 00:56 UTC
Labels: bug, question
