### ISSUE TITLE
how to find the maximum and minimum value of a function

### ISSUE THREAD

**Issue by pomaton12** [ncalc/ncalc#94] opened 2023-12-24 21:01 UTC
Hello, is there a way to calculate the maximum value and the minimum value of a function declared in string function = "x^2 +2" within a range 0 - 10

**Comment by gumbarros** [comment] 2023-12-25 13:30
Merry Christmas🎅🎄

Is this snippet what you need?

```cs

using NCalc;

string function = "x^2 + 2";

Expression expression = new(function);


double maxValue = double.MinValue;
double maxArg = 0;
double minValue = double.MaxValue;
double minArg = 0;

for (double x = 0; x <= 10; x++)
{
    expression.Parameters["x"] = x;
    var result = Convert.ToDouble(expression.Evaluate());

    if (result > maxValue)
    {
        maxValue = result;
        maxArg = x;
    }

    if (result < minValue)
    {
        minValue = result;
        minArg = x;
    }
}

Console.WriteLine($"Maximum value: {maxValue} at x = {maxArg}");
Console.WriteLine($"Minimum value: {minValue} at x = {minArg}");
```

<img width="172" alt="image" src="https://github.com/ncalc/ncalc/assets/52143624/8747a54d-d2a4-47fd-93f7-9c0f45b5a0be">

**Comment by Bykiev** [comment] 2024-03-20 11:36
You can also use array parameters like this:
https://github.com/ncalc/ncalc/blob/08994e2c366d4f2621aeea461c0e12ac1448dbf4/test/NCalc.Tests/Fixtures.cs#L535-L544

**Comment by gumbarros** [comment] 2024-04-22 01:45
@pomaton12  feel free to close the issue if your problem is solved.

**Comment by Bykiev** [comment] 2024-11-03 09:29
The issue is closed due to inactivity. Feel free to reopen if you have any questions.

**Closed by Bykiev** 2024-11-03 09:29 UTC
Labels: needs author feedback
