### ISSUE TITLE
5.3.0.0 NCalc.Sync.signed "Invalid token in expression at position (1:1)" for some parameter names

### ISSUE THREAD

**Issue by Stephen-Lamb1** [ncalc/ncalc#372] opened 2024-12-09 18:31 UTC
**Describe the bug**
The 5.3.0.0 .NET Framework version of LogicalExpressionParser.Parse raises NCalcParserException Message = "Invalid token in expression at position (1:1)" when passed a context with a single char parameter name expression when not surrounded by []. This wasn't happening with 5.2.11.

**Example Expression**

`namespace ConsoleApp41
{
    using System;
    using System.Collections.Generic;
    using NCalc;
    using NCalc.Parser;

    internal class Program
    {
        static void Main(string[] args)
        {
            var chars = new List<string>();
            for (var c = 'a'; c < 'z'; ++c)
            {
                chars.Add(c.ToString());
            }

            for (var c = 'A'; c < 'Z'; ++c)
            {
                chars.Add(c.ToString());
            }

            var failed = new List<string>();
            foreach (var c in chars)
            {
                try
                {
                    var context = new LogicalExpressionParserContext(c, ExpressionOptions.None);
                    LogicalExpressionParser.Parse(context);
                }
                catch (Exception)
                {
                    failed.Add(c);
                }
            }

            var fails = string.Join(",", failed);
            Console.WriteLine("Failed: " + fails);
        }
    }
}
`

Output:
![image](https://github.com/user-attachments/assets/8728a4c3-d7db-44a7-b8eb-e50c982f6521)

**Comment by gumbarros** [comment] 2024-12-12 22:51
Are you sure that you are using v5.3.0.0? The unit test works normally here:

```cs
    [Fact]
    public void ShouldNotFailIssue372()
    {
        var chars = new List<string>();
        for (var c = 'a'; c < 'z'; ++c)
        {
            chars.Add(c.ToString());
        }

        for (var c = 'A'; c < 'Z'; ++c)
        {
            chars.Add(c.ToString());
        }

        var failed = new List<string>();
        foreach (var c in chars)
        {
            try
            {
                var context = new LogicalExpressionParserContext(c, ExpressionOptions.None);
                LogicalExpressionParser.Parse(context);
            }
            catch (Exception)
            {
                failed.Add(c);
            }
        }

        Assert.Empty(failed);
    }
    ``` 
    
![image](https://github.com/user-attachments/assets/7887c75d-ea66-42ff-82f8-03d48dd94a84)
(I'm on Linux and don't have .NET Framework)

**Comment by Stephen-Lamb1** [comment] 2024-12-13 14:32
Yes, I'm certain the code is using the 5.3.0.0 version of NCalc as I've added code to write out the full name of the assembly for an NCalc type, e.g. Console.WriteLine(context.GetType().Assembly.FullName);.

I tested with NCalcSync and NCalcSync.signed and get the same issue for .NET Framework 4.8 projects. .NET 8.0 on Windows 10 was tested, and it does not have this issue.

**Comment by Stephen-Lamb1** [comment] 2024-12-13 19:15
This issue has also been duplicated on a colleagues machine.

**Comment by gumbarros** [comment] 2024-12-14 22:26
@Bykiev can you check the unit test at .NET Framework? I don't have a Windows machine.

**Comment by gumbarros** [comment] 2024-12-15 18:38
Created unit test https://github.com/ncalc/ncalc/pull/377

**Comment by gumbarros** [comment] 2024-12-18 00:55
If someone can repro this with a unit test, help is appreciated.

**Comment by Bykiev** [comment] 2024-12-22 08:01
> var chars = new List<string>();
>         for (var c = 'a'; c < 'z'; ++c)
>         {
>             chars.Add(c.ToString());
>         }
> 
>         for (var c = 'A'; c < 'Z'; ++c)
>         {
>             chars.Add(c.ToString());
>         }
> 
>         var failed = new List<string>();
>         foreach (var c in chars)
>         {
>             try
>             {
>                 var context = new LogicalExpressionParserContext(c, ExpressionOptions.None);
>                 LogicalExpressionParser.Parse(context);
>             }
>             catch (Exception)
>             {
>                 failed.Add(c);
>             }
>         }
> 
>         var fails = string.Join(",", failed);
>         Console.WriteLine("Failed: " + fails);

Hi, I've tried to reproduce the issue on .NET Framework with no luck, the sample is working as expected

**Comment by Bykiev** [comment] 2024-12-22 08:27
@Stephen-Lamb1, can you please create a test project with this issue and attach a compiled executable?

**Comment by Stephen-Lamb1** [comment] 2024-12-23 16:49
[ConsoleApp39.zip](https://github.com/user-attachments/files/18231497/ConsoleApp39.zip)
[ConsoleApp47.zip](https://github.com/user-attachments/files/18231502/ConsoleApp47.zip)

Attached are the directories of the solutions and the compiled binaries. ConsoleApp39 was created back on the 9th of December and built with 5.3.0.0. At the time, I updated all nuget packages for that solution - just NCalc and its dependencies. If you run that exe, it will still show the failures.

This AM I tried again, first with the latest version 5.3.1.0 and could not reproduce the issue. I then went back and tried again, ConsoleApp47, with 5.3.0.0, but this time, I didn't update any nuget packages. I still couldn't reproduce the issue.

Here are the binary differences between the output folders of the console applications. Maybe there was/is a conflict with one of the DLLs that are different between the two console apps? As I said previously, I had a colleague duplicate the issue so there was/is an issue.
![image](https://github.com/user-attachments/assets/5a39bacd-a5ae-48c6-af82-cc54d5ce754b)

**Comment by Bykiev** [comment] 2024-12-23 17:20
`NCalc 5.3.0` had a dependency on `Parlot 1.0.2`, but it seems you've updated the transitive dependency `Parlot` to v1.2.3. This release had an issue (you can check the CI build results [here](https://github.com/ncalc/ncalc/actions/runs/12240544505/job/34143618654) with the same errors).

Feel free to close the issue if the problem is resolved.

**Closed** 2024-12-26 16:03 UTC
Labels: bug, help wanted
