### ISSUE TITLE
StackOverflow Exception on Evaluate function

### ISSUE THREAD

**Issue by PuneetG123** [ncalc/ncalc#167] opened 2024-05-24 11:43 UTC
I am getting StackOverflow exception on evaluate function and I guess this is because of long precision numbers not sure though as the exception doesn't have much details in it whereas the same evaluation was working fine on NCalc 3.10.0 version.

**Comment by PuneetG123** [comment] 2024-05-24 13:01
Hi
Below is my expression:
((((A * (B / 4)) + ((1 - A) * (C / 8))) * D) + E)
Where A, B, C, D, E are considered as array of length 300. I am using ExpressionOptions.IterateParamter option during evaluation.

**Comment by gumbarros** [comment] 2024-05-25 14:00
@PuneetG123 good morning,

Can you send a snippet setting the parameters and evaluating so I can write a unit test and fix?

**Comment by PuneetG123** [comment] 2024-05-27 08:33
Good Morning,

Below is the code snippet that I am using to set the parameters:

for (int i = 0; i < iTotalNumRecords; i++)
{
	int counter = 0;
	Expression e = new Expression(expText, EvaluateOptions.IterateParameters);
	e.EvaluateFunction += EvaluateFunctionExpression;
	foreach (string str in lArguments)
	{

	List<double> d1 = new List<double>(lArguments1[counter][i].Replace("{", "").Replace("}", "").Split(',').Select(double.Parse).ToList());
	e.Parameters.Add(str, d1);

	counter++;
	}
	var d2 =  (object)e.Evaluate();
	string d3 = "{" + string.Join(",", ((List<object>)d2).ToArray()) + "}";
	lResult.Add(d3);
}

In the above code there are 2 lists 

1. lArgments : Contains the name of the of parameters like inthe above expression it is A,B, C etc..
2. lArguments1 : Contains the value corresponds to that parameter. Which is also a list of numeric values.

Please let me know if you need anything else from my side.

Thanks

**Comment by gumbarros** [comment] 2024-05-27 23:27
> Good Morning,
> 
> Below is the code snippet that I am using to set the parameters:
> 
> for (int i = 0; i < iTotalNumRecords; i++) { int counter = 0; Expression e = new Expression(expText, EvaluateOptions.IterateParameters); e.EvaluateFunction += EvaluateFunctionExpression; foreach (string str in lArguments) {
> 
> ```
> List<double> d1 = new List<double>(lArguments1[counter][i].Replace("{", "").Replace("}", "").Split(',').Select(double.Parse).ToList());
> e.Parameters.Add(str, d1);
> 
> counter++;
> }
> var d2 =  (object)e.Evaluate();
> string d3 = "{" + string.Join(",", ((List<object>)d2).ToArray()) + "}";
> lResult.Add(d3);
> ```
> 
> }
> 
> In the above code there are 2 lists
> 
> 1. lArgments : Contains the name of the of parameters like inthe above expression it is A,B, C etc..
> 2. lArguments1 : Contains the value corresponds to that parameter. Which is also a list of numeric values.
> 
> Please let me know if you need anything else from my side.
> 
> Thanks

I think you need to change:
```cs
string d3 = "{" + string.Join(",", ((List<object>)d2).ToArray()) + "}";
```
to
```cs
string d3 = "{" + string.Join(",", ((List<object>)d2.Evalute()).ToArray()) + "}";
```
Because this would cause a infinite recursive loop, `I think`, help from outside is appreciated.

**Comment by Beckdotan** [comment] 2024-06-30 04:55
I also have stackOverFlow exception problem when I deal with arrays. but since I have my own visitor I'm not using the .Evaluate() syntax at all. 

[Full description described in issue 192](https://github.com/ncalc/ncalc/issues/192#issuecomment-2186807425), but i also noticed that I get that only when I use '()' in my expression.

**Comment by gumbarros** [comment] 2024-06-30 13:26
> I also have stackOverFlow exception problem when I deal with arrays. but since I have my own visitor I'm not using the .Evaluate() syntax at all.
> 
> [Full description described in issue 192](https://github.com/ncalc/ncalc/issues/192#issuecomment-2186807425), but i also noticed that I get that only when I use '()' in my expression.

Can you share the stacktrace of the exception? So we can check if it's a parser exception or a custom evaluation exception

**Comment by Beckdotan** [comment] 2024-07-02 05:22
the stacktrace seems to be "null"
<img width="683" alt="image" src="https://github.com/ncalc/ncalc/assets/78174171/be6b66fd-29f2-46c8-a737-fab4a0ba03bd">


But i might have another clue: 

Despite the fact I'm using .net framework 4.8 in my project, this part of the code in Ncalc is bright, and not the "under 6.0". 

in my project I add the NCalc project manually (and no thought NuGet) so I can see what is going on. 

this is the settings of it: 
<img width="680" alt="image" src="https://github.com/ncalc/ncalc/assets/78174171/0faf3905-062e-420a-8687-df9a75702d0f">

but it does stop there:
<img width="383" alt="image" src="https://github.com/ncalc/ncalc/assets/78174171/34bf8ffb-ba79-4551-881d-e19bffa0ba0a">

**Comment by gumbarros** [comment] 2024-07-02 13:02
> @gumbarros Thanks!
> 
> the stacktrace seems to be "null" <img alt="image" width="683" src="https://private-user-images.githubusercontent.com/78174171/344885340-be6b66fd-29f2-46c8-a737-fab4a0ba03bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MjU2MTksIm5iZiI6MTcxOTkyNTMxOSwicGF0aCI6Ii83ODE3NDE3MS8zNDQ4ODUzNDAtYmU2YjY2ZmQtMjlmMi00NmM4LWE3MzctZmFiNGEwYmEwM2JkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDEzMDE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMjBkNmY3MTZiYjYzNzI4MGY1YTk2YWM2YWFjY2I3MDQ2NDIyOTRjNTVlMTliMzQxZGFhOGZlNDFmYzU5ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y9dYwOr2SJOJOnp-eIuLnsF0IhW77yRsVSvlL59nNdk">
> 
> But i might have another clue:
> 
> Despite the fact I'm using .net framework 4.8 in my project, this part of the code in Ncalc is bright, and not the "under 6.0". <img alt="image" width="314" src="https://private-user-images.githubusercontent.com/78174171/344886696-173bb5de-9597-4c28-87ed-39dc5496ac9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MjU2MTksIm5iZiI6MTcxOTkyNTMxOSwicGF0aCI6Ii83ODE3NDE3MS8zNDQ4ODY2OTYtMTczYmI1ZGUtOTU5Ny00YzI4LTg3ZWQtMzlkYzU0OTZhYzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDEzMDE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzODg3MzlmYjAzMGZhMTYwY2MxNzhmYWM5ODYxMjY5M2YyOTdmNmI0MGUyZjc0ZDRlMjUwYzhkNDI0NTU0OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f7azlu1R29YQ8RlAnBLXJQoCyyAOwzs41WQge73zLAg">
> 
> in my project I add the NCalc project manually (and no thought NuGet) so I can see what is going on.
> 
> this is the settings of it: <img alt="image" width="680" src="https://private-user-images.githubusercontent.com/78174171/344885722-0faf3905-062e-420a-8687-df9a75702d0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MjU2MTksIm5iZiI6MTcxOTkyNTMxOSwicGF0aCI6Ii83ODE3NDE3MS8zNDQ4ODU3MjItMGZhZjM5MDUtMDYyZS00MjBhLTg2ODctZGY5YTc1NzAyZDBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDEzMDE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiMTkzYzZiNmIyNzUyYjk2YmYzYzQyNmJiYjRmYzFiMWVmYTRmYmU4MTQ1ZDQ0NjIyMzdhNmUzODU0N2M0NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yz7ee9gL3C1YnkILC33n9ODYAHbkd_PTgEt40nsJyD8">
> 
> but it does stop there: <img alt="image" width="383" src="https://private-user-images.githubusercontent.com/78174171/344886513-34bf8ffb-ba79-4551-881d-e19bffa0ba0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MjU2MTksIm5iZiI6MTcxOTkyNTMxOSwicGF0aCI6Ii83ODE3NDE3MS8zNDQ4ODY1MTMtMzRiZjhmZmItYmE3OS00NTUxLTg4MWQtZTE5YmZmYTBiYTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDEzMDE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNWU1ODIwNDgyYmVmNWMxNDQwODk5ZWZkNWJkYWM0YjY0ZmZmM2JiOTg5YzlkYWUzNTM1MjEwYTczNmRjZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6E-8_xVbl--ilndyEXhEHVjit_qrumF8lDPU2hQJ3L8">

Try removing .Compile

**Comment by Beckdotan** [comment] 2024-07-03 05:49
@gumbarros 

Thanks. 
Can you explain what this .compile does? since when I delete it, it seems to be working fine, so I'm wondering if it is necessary at all. 


I'm waiting for updating for a verry long time to get the running time benefits from all your  amazing hard work! 

Please also have a look at the other bug i opened there is full details there as well:
[](https://github.com/ncalc/ncalc/issues/192
)

**Comment by Bykiev** [comment] 2024-07-03 06:14
From the Parlot [docs](https://github.com/sebastienros/parlot?tab=readme-ov-file#compilation):

> Grammar trees built using the Fluent API can optionally be compiled with the Compile() method. At that point, instead of evaluating recursively all the parsers in the grammar tree, these are converted to a more linear and optimized but equivalent compiled IL. This can improve the performance by 20% (see benchmarks results).

If it's working without compilation then you should create an issue in Parlot repo.

**Comment by Beckdotan** [comment] 2024-07-03 06:29
@Bykiev  I feel like we are going in circles, since I already did all this tests  in the other bug I [opened](https://github.com/ncalc/ncalc/issues/192), I want told to open a bug in [parlot](https://github.com/sebastienros/parlot/issues/129), which they closed saying that they are following on my bug in this repository. 


@Bykiev  @gumbarros  can you please explain what this .conpile does? why is it working withpout it (but just without the calculation time improvments?).  

@sebastienros can you please help me find the problem? whether in this bug or in my original one?

**Comment by sebastienros** [comment] 2024-07-03 06:58
@Beckdotan In theory if it works without compile I am pretty sure this could be an issue in Parlot, but here we have some code that we can work with, we have nothing at all to work with in the Parlot repository. Once I know what the issue is "with Parlot" then we can add an issue there.

Back to your issue (the other one), until you can provide a way to reproduce the problem then we won't be able to help. And even more, and it would be very helpful if you could help us repro the problem in a unit test that is minimal, not involving so many components. Based on your original comment it should be as simple as executing the expression you shared, but it doesn't look like so, and AFAIR as you were not able to create some code that fails outside of your own application. At least please add more of the stacktrace that shows where the actual overflow happens (to exclude one coming from your own custom functions).

General comment about `Compile()`:

Instead of evaluating a bunch of conditions to drive what has to be done on each execution, Parlot can decide which code to execute once and create an Expression Tree that is then compiled. Another example is when `SkipAnd` is called, it know the value can be discarded, so it won't try to materialize a value, more like pattern matching. In the end it's makes parsing faster. All the tests in Parlot are executed with and without compilation to ensure it works but there might be gaps so it's not bug-free, either way.

**Comment by sebastienros** [comment] 2024-07-03 07:01
I think we should close this local issue as there was not answer from the author, the suggestion might have worked.

@Beckdotan your issue might be totally different, we should continue on the other issue you created. I don't see any reason to think it's the same SO exception.

**Closed** 2024-07-08 19:54 UTC
Labels: bug, help wanted
