### ISSUE TITLE
The collection's state is no longer correct Exception

### ISSUE THREAD

**Issue by Coder3333** [ncalc/ncalc#10] opened 2019-02-25 21:57 UTC
I randomly get this exception when calling Evaluate from the middleware of my ASP.Net Core web application. All I do is pass a string into the expression. I cannot think of any way that I can be affecting any collections in a non-concurrent way. Any suggestions?

Sometimes I get this error:
> NCalc.EvaluationException: Operations that change non-concurrent collections must have exclusive access.
> A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.     at NCalc.Expression.Evaluate()

Sometimes the error looks like this:
> NCalc.EvaluationException: Collection was modified; enumeration operation may not execute.     at NCalc.Expression.Evaluate()     

```
            var eap = new NCalc.Expression(expression);
            return eap.Evaluate();
```

**Comment by yallie** [comment] 2019-02-26 09:12
Could you please create a unit test to demonstrate the issue?
I'd be glad to accept a PR.

**Comment by Coder3333** [comment] 2019-02-26 13:02
The expression I am using is something as simple as the string "400 = 200", which I expect to return false.  I have never been able to replicate the issue in a unit tests.  I only see it in production, which makes me think there is a static collection somewhere in the code that is being shared by threads, but I have not been able to find it.

**Comment by Coder3333** [comment] 2019-03-13 18:11
I am starting to think this is a bug in .Net Core.  I am going to update to Microsoft.AspNetCore.All 2.2.3 from 2.0.0 and see if the issue goes away.

**Comment by yallie** [comment] 2019-03-14 08:16
Yes, that looks suspicious.
By the way, does the issue reproduce when you set `CacheEnabled = false`?

**Comment by codermrrob** [comment] 2019-07-23 08:23
I am also getting this error in production. It happens rarely and I have been unable to reproduce it in a dev/testing environment.

Expressions are always simple. The most recent fail was evaluating 403 * -1

My suspicions have also been on the static dictionary. I will disable the cache, and it seems like that will stop using the static dictionary.

**Comment by gumbarros** [comment] 2024-03-29 22:20
@codermrrob we are now using a `ConcurrentDictionary` at v3.12, now the cache is truly thread-safe. Feel free to close the issue if everything is working or more details if the error still happens.

**Comment by gumbarros** [comment] 2024-05-25 18:31
Closed due inactivity

**Closed** 2024-05-25 18:31 UTC
Labels: needs author feedback
